server {
    listen 80;
    index index.php index.html;
    root /var/www/html; # Chemin vers votre code

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Passe toutes les requêtes .php au conteneur PHP-FPM
    location ~ \.php$ {
        fastcgi_pass foot-php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
